### ISSUE TITLE
NullPointerException in XeroOAuthService

### ISSUE THREAD

**Issue by riankruger** [connectifier/xero-java-client#16]
Hi 

I am getting the following error:

Exception in thread "main" java.lang.NullPointerException
	at com.connectifier.xeroclient.oauth.XeroOAuthService.<init>(XeroOAuthService.java:32)
	at com.connectifier.xeroclient.XeroClient.<init>(XeroClient.java:74)
	at com.geniisystems.XeroService.<init>(XeroService.java:32)
	at com.geniisystems.XeroService.main(XeroService.java:43)

This is because "pemParser.readObject()" is returning null.

I've checked that the key pair file path is correct.

I generated the keypair as described by xero:

openssl genrsa -out privatekey.pem 1024
openssl req -new -x509 -key privatekey.pem -out publickey.cer -days 1825
openssl pkcs12 -export -out public_privatekey.pfx -inkey privatekey.pem -in publickey.cer

I've tried with and without a password.

EDIT: It seems that the java code is expecting a PEM key pair but the key pair is pkcs12. Can you confirm how I should be generating the pem key pair. When I follow examples like: https://rietta.com/blog/2012/01/27/openssl-generating-rsa-key-from-command/ xero does not accept the public key, it is not in the correct format.
 
Any suggestions would be much appreciated.

Thanks

Rian

**Comment by riankruger** [comment]
Sorry, it is late... I am not thinking straight.

I must skip the 3rd step when generating the key and cert, this works:

openssl genrsa -out privatekey.pem 1024
openssl req -new -x509 -key privatekey.pem -out publickey.cer -days 1825
