### ISSUE TITLE
Marshalling and unmarshalling

### ISSUE THREAD

**Issue by livewithattitude** [connectifier/xero-java-client#21]
Hi Guys,
Thank you for this module. I know that it is not maintained, just had an issue with this and thought to get some ideas on fixing this. It was working fine on a client environment until a month back, but now when I try we get this error. 

	at com.connectifier.xeroclient.XeroClient.unmarshallResponse(XeroClient.java:159)
	at com.connectifier.xeroclient.XeroClient.get(XeroClient.java:125)
	at com.connectifier.xeroclient.XeroClient.get(XeroClient.java:107)
	at com.connectifier.xeroclient.XeroClient.getContacts(XeroClient.java:232)
	at Test.main(Test.java:15)
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 2 of 3-byte UTF-8 sequence.]
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(Unknown Source)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(Unknown Source)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(Unknown Source)
	at com.connectifier.xeroclient.XeroClient.unmarshallResponse(XeroClient.java:157)
	... 4 more
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 2 of 3-byte UTF-8 sequence.
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at 

com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	... 8 more

Any suggestions on the possible cause?

**Comment by livewithattitude** [comment]
Fixed it. It was an issue with duplicate libraries
